# Generated by Django 4.1.3 on 2022-12-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_phone_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='old_price',
            field=models.IntegerField(default=0),
        ),
    ]
