# Generated by Django 4.1.3 on 2022-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('other_name', models.CharField(default='', max_length=20)),
                ('reg_number', models.CharField(max_length=16)),
            ],
        ),
    ]
